Latest updates for Last Mile Fleet Solution Sample Apps.
googlemaps/last-mile-fleet-solution-samples pull request #40
Opened 2022-05-27 23:10 UTC by leovitch

Latest updates for Last Mile Fleet Solution Sample Apps.

2022-05-28 01:36 UTC, yuethomas approved these changes

2022-05-31 18:30 UTC, wangela requested changes
Please request review again when code has been updated so that all checks have been cleared.

2022-05-31 18:50 UTC, yuethomas commented
Hello Angela!

 - cla/google: we're modifying our config to use another bot account to submit. 
 - CI builds: these will not work because LMFS Sample Apps require special configurations, which are infeasible with Github Actions right now. I will ping you a write up on these issues.

2022-06-02 23:15 UTC, amuramoto approved these changes

2022-06-02 23:24 UTC, leovitch commented
Angela's original request was to make the CI builds run, however as Tom mentioned this is currently impossible.

Got Alex to also take a look. Since Angela is OOO, will merge without waiting.

2022-06-02 23:26 UTC, merged